const $=id=>document.getElementById(id);const audio=$('audio');
const DB='fk-music-v5',VER=2;let db,songs=[],playlists=[],current=-1,objectURL=null,coverURL=null,shuffle=false,repeat=false,deferred=null;
const els={title:$('title'),artist:$('artist'),album:$('album'),cover:$('cover'),ring:$('ring'),play:$('play'),prev:$('prev'),next:$('next'),seek:$('seek'),cur:$('cur'),dur:$('dur'),fav:$('favoriteNow'),search:$('search'),list:$('songList'),empty:$('empty'),favs:$('favorites'),favEmpty:$('favEmpty'),pls:$('playlists'),plEmpty:$('playlistEmpty')};
function fmt(n){if(!Number.isFinite(n))return'0:00';return Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0')}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('songs'))d.createObjectStore('songs',{keyPath:'id'});if(!d.objectStoreNames.contains('playlists'))d.createObjectStore('playlists',{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const all=s=>new Promise((res,rej)=>{let r=db.transaction(s,'readonly').objectStore(s).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});const put=(s,v)=>new Promise((res,rej)=>{let r=db.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});const del=(s,k)=>new Promise((res,rej)=>{let r=db.transaction(s,'readwrite').objectStore(s).delete(k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fallback(name){let n=name.replace(/\.[^/.]+$/,'');let p=n.split(' - ');return p.length>1?{artist:p[0],title:p.slice(1).join(' - ')}:{artist:'Unknown Artist',title:n}}
function decode(bytes,enc){try{return new TextDecoder(enc===1||enc===2?'utf-16':enc===0?'windows-1252':'utf-8').decode(bytes).replace(/\0/g,'').trim()}catch{return new TextDecoder().decode(bytes).replace(/\0/g,'').trim()}}
function sync(b){return(b[0]&127)<<21|(b[1]&127)<<14|(b[2]&127)<<7|(b[3]&127)}
async function id3(file){if(!/\.mp3$/i.test(file.name)&&file.type!=='audio/mpeg')return{};let b=new Uint8Array(await file.slice(0,1024*1024).arrayBuffer());if(b.length<10||String.fromCharCode(...b.slice(0,3))!=='ID3')return{};let major=b[3],size=sync(b.slice(6,10)),p=10,end=Math.min(b.length,10+size),o={};while(p<end-10){let id,sz;if(major===2){id=String.fromCharCode(...b.slice(p,p+3));sz=(b[p+3]<<16)|(b[p+4]<<8)|b[p+5];p+=6}else{id=String.fromCharCode(...b.slice(p,p+4));sz=major===4?sync(b.slice(p+4,p+8)):((b[p+4]<<24)>>>0)|(b[p+5]<<16)|(b[p+6]<<8)|b[p+7];p+=10}if(!id||!sz)break;let f=b.slice(p,Math.min(end,p+sz));p+=sz;if(['TIT2','TT2','TPE1','TP1','TALB','TAL','TPE2'].includes(id)){let k=id.startsWith('TIT')?'title':id.startsWith('TAL')?'album':'artist';if(!o[k])o[k]=decode(f.slice(1),f[0])}if(id==='APIC'&&f.length&&!o.cover){let enc=f[0],q=1;while(q<f.length&&f[q]!==0)q++;let mime=new TextDecoder().decode(f.slice(1,q))||'image/jpeg';q++;q++;if(enc===0||enc===3){while(q<f.length&&f[q]!==0)q++;q++}else{while(q+1<f.length&&(f[q]!==0||f[q+1]!==0))q+=2;q+=2}o.cover=new Blob([f.slice(q)],{type:mime})}}return o}
function setCover(song){if(coverURL)URL.revokeObjectURL(coverURL);coverURL=null;if(song?.cover){coverURL=URL.createObjectURL(song.cover);els.cover.style.backgroundImage=`url("${coverURL}")`;els.cover.querySelector('span').style.display='none'}else{els.cover.style.backgroundImage='linear-gradient(135deg,#7440d8,#a8e5dc)';els.cover.querySelector('span').style.display='block'}}
function coverHTML(s){if(s.cover){let u=URL.createObjectURL(s.cover);setTimeout(()=>URL.revokeObjectURL(u),30000);return`<img class="song-cover" src="${u}" alt="">`}return'<div class="song-cover">♫</div>'}
async function addFiles(files,source='user'){let added=0;for(let f of files){if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav|ogg|flac|opus)$/i.test(f.name))continue;let m=await id3(f),fb=fallback(f.name);let s={id:crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random(),file:f,name:m.title||fb.title,artist:m.artist||fb.artist,album:m.album||'Unknown Album',cover:m.cover||null,favorite:false,addedAt:Date.now(),source};songs.push(s);await put('songs',s);added++}render();toast(added?`${added} audio file${added>1?'s':''} added`:'No supported audio files selected')}
function render(){let q=els.search.value.toLowerCase().trim();els.list.innerHTML='';let vis=songs.map((s,i)=>({...s,i})).filter(s=>`${s.name} ${s.artist} ${s.album}`.toLowerCase().includes(q));els.empty.style.display=vis.length?'none':'block';vis.forEach(s=>{let r=document.createElement('div');r.className='song'+(s.i===current?' active':'');r.innerHTML=`${coverHTML(s)}<div><div class="song-name">${esc(s.name)}</div><div class="song-meta">${esc(s.artist)} · ${esc(s.album)}</div></div><button class="song-action ${s.favorite?'active':''}">${s.favorite?'♥':'♡'}</button><button class="song-action remove">✕</button>`;r.onclick=e=>{if(e.target.closest('button'))return;load(s.i,true)};r.querySelector('.song-action').onclick=e=>{e.stopPropagation();toggleFav(s.i)};r.querySelector('.remove').onclick=e=>{e.stopPropagation();removeSong(s.i)};els.list.appendChild(r)});renderFavs();renderPls();$('songCount').textContent=songs.length;$('favCount').textContent=songs.filter(s=>s.favorite).length}
function renderFavs(){els.favs.innerHTML='';let f=songs.map((s,i)=>({...s,i})).filter(s=>s.favorite);els.favEmpty.style.display=f.length?'none':'block';f.forEach(s=>{let r=document.createElement('div');r.className='mini-item';r.innerHTML=`${coverHTML(s).replace('song-cover','mini-cover')}<div class="mini-main"><strong>${esc(s.name)}</strong><span>${esc(s.artist)}</span></div><button class="song-action active">♥</button>`;r.onclick=e=>{if(e.target.closest('button'))return;load(s.i,true)};r.querySelector('button').onclick=e=>{e.stopPropagation();toggleFav(s.i)};els.favs.appendChild(r)})}
function renderPls(){els.pls.innerHTML='';els.plEmpty.style.display=playlists.length?'none':'block';playlists.forEach(p=>{let r=document.createElement('div');r.className='mini-item';r.innerHTML=`<div class="mini-cover">♫</div><div class="mini-main"><strong>${esc(p.name)}</strong><span>${p.ids.length} songs</span></div><button class="song-action">✕</button>`;r.onclick=e=>{if(e.target.closest('button'))return;let idx=p.ids.map(id=>songs.findIndex(s=>s.id===id)).find(i=>i>=0);if(idx!=null)load(idx,true)};r.querySelector('button').onclick=async e=>{e.stopPropagation();playlists=playlists.filter(x=>x.id!==p.id);await del('playlists',p.id);render()};els.pls.appendChild(r)})}
async function toggleFav(i){if(!songs[i])return;songs[i].favorite=!songs[i].favorite;await put('songs',songs[i]);render();if(i===current){els.fav.textContent=songs[i].favorite?'♥':'♡';els.fav.classList.toggle('active',songs[i].favorite)}toast(songs[i].favorite?'Added to favorites':'Removed from favorites')}
async function removeSong(i){if(!confirm(`Remove “${songs[i].name}”?`))return;if(i===current){audio.pause();audio.removeAttribute('src');current=-1;els.title.textContent='No song selected';els.artist.textContent='Choose music from Audio';els.album.textContent='Unknown Album';setCover(null)}else if(i<current)current--;let id=songs[i].id;songs.splice(i,1);await del('songs',id);render();toast('Song removed')}
async function load(i,auto=false){if(!songs[i])return;current=i;if(objectURL)URL.revokeObjectURL(objectURL);objectURL=URL.createObjectURL(songs[i].file);audio.src=objectURL;els.title.textContent=songs[i].name;els.artist.textContent=songs[i].artist;els.album.textContent=songs[i].album;els.fav.textContent=songs[i].favorite?'♥':'♡';els.fav.classList.toggle('active',songs[i].favorite);setCover(songs[i]);els.seek.value=0;els.cur.textContent='0:00';els.dur.textContent='0:00';els.ring.style.setProperty('--p','0%');render();if(auto)audio.play().catch(()=>toast('Tap Play to start audio'))}
function next(){if(!songs.length)return;let i;if(shuffle&&songs.length>1){do i=Math.floor(Math.random()*songs.length);while(i===current)}else i=current<0?0:(current+1)%songs.length;load(i,true)}
function show(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));document.querySelector('.topbar h1').textContent=page==='home'?'Now Playing':page==='audio'?'Audio':'Me'}
function theme(){let dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);localStorage.setItem('fk-theme',dark?'dark':'light');$('themeBtn').textContent=dark?'☀':'☼'}
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2200)}
$('fileInput').addEventListener('change',e=>{addFiles([...e.target.files]);e.target.value=''});$('addQuick').onclick=()=>$('audioPicker').click();$('audioPicker').addEventListener('change',e=>{addFiles([...e.target.files]);e.target.value=''});
$('play').onclick=()=>{if(!audio.src&&songs.length)load(0);if(audio.src)audio.paused?audio.play():audio.pause()};$('prev').onclick=()=>songs.length&&load(current<=0?songs.length-1:current-1,true);$('next').onclick=next;$('shuffle').onclick=()=>{shuffle=!shuffle;$('shuffle').classList.toggle('active',shuffle)};$('repeat').onclick=()=>{repeat=!repeat;$('repeat').classList.toggle('active',repeat)};els.fav.onclick=()=>current>=0&&toggleFav(current);
$('back10').onclick=()=>audio.src&&(audio.currentTime=Math.max(0,audio.currentTime-10));$('forward10').onclick=()=>audio.src&&(audio.currentTime=Math.min(audio.duration||0,audio.currentTime+10));$('speedBtn').onclick=()=>{let a=[1,1.2,1.5,2,.8],i=a.indexOf(audio.playbackRate),n=a[(i+1)%a.length];audio.playbackRate=n;$('speedBtn').textContent=n+'x'};
$('seek').oninput=()=>{if(audio.duration)audio.currentTime=audio.duration*($('seek').value/100)};audio.addEventListener('loadedmetadata',()=>els.dur.textContent=fmt(audio.duration));audio.addEventListener('timeupdate',()=>{if(audio.duration){let p=audio.currentTime/audio.duration*100;els.seek.value=p;els.ring.style.setProperty('--p',p+'%')}els.cur.textContent=fmt(audio.currentTime)});audio.addEventListener('play',()=>{els.play.textContent='Ⅱ';els.cover.classList.add('playing')});audio.addEventListener('pause',()=>{els.play.textContent='▶';els.cover.classList.remove('playing')});audio.addEventListener('ended',()=>repeat?load(current,true):next());
$('themeBtn').onclick=theme;$('themeRow').onclick=theme;$('historyBtn').onclick=()=>toast('Recently played is coming soon');$('queueBtn').onclick=()=>show('audio');$('sleepRow').onclick=()=>toast('Sleep timer is coming soon');$('backBtn').onclick=()=>show('home');document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));els.search.oninput=render;
$('newPlaylist').onclick=()=>{let d=$('playlistDialog');$('playlistName').value='';d.showModal();setTimeout(()=>$('playlistName').focus(),30)};$('cancelPlaylist').onclick=()=>$('playlistDialog').close();$('playlistForm').onsubmit=async e=>{e.preventDefault();let n=$('playlistName').value.trim();if(!n)return;let p={id:crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random(),name:n,ids:[]};playlists.push(p);await put('playlists',p);$('playlistDialog').close();render();toast('Playlist created')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$('installBtn').hidden=true};
async function seedBuiltIn(){let exists=songs.some(s=>s.source==='demo');if(exists)return;let names=['Voice Note 01','Voice Note 02','Voice Note 03','Voice Note 04','Voice Note 05'];for(let i=1;i<=5;i++){let r=await fetch(`audio/track-${i}.ogg`);let b=await r.blob();let s={id:'demo-'+i,file:b,name:names[i-1],artist:'FK Music',album:'Demo Library',cover:null,favorite:false,addedAt:Date.now()+i,source:'demo'};songs.push(s);await put('songs',s)}}
async function init(){document.body.classList.toggle('dark',localStorage.getItem('fk-theme')==='dark');$('themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☼';try{db=await openDB();songs=await all('songs');playlists=await all('playlists');await seedBuiltIn();render()}catch(e){console.error(e);toast('Storage unavailable. You can still try Add Music.')}if('serviceWorker'in navigator)navigator.serviceWorker.register('pwabuilder-sw.js').catch(()=>{})}init();